### ISSUE TITLE
Use the cloud-health-agent inside a docker container inside an EC2

### ISSUE THREAD

**Issue by pastjean** [CloudHealth/agent-install-helpers#4]
I wanna run the cloud-health-agent inside a kubernetes cluster on ec2. I'd prefer not having to run it directly on the host.

Here's something i cooked up for it to work:
https://github.com/coveo/docker-cloud-health-agent

There is a bug or limitation in the lib that is used to detect machine information that when you run in docker limits the ability to see ec2 instance metadata. If that could be fixed it would help a lot

**Comment by srflaxu40** [comment]
anything on this?

**Comment by AnirbanKundu** [comment]
What is the outcome of this issue? Looks like it is closed?
